version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=clients'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5432"

    networks:
      - backend

  app:
    build: /.
    container_name: 'clients-java-app'
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/clients'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=0000'
      - 'SPRING_PROFILES_ACTIVE=default,redis'

    depends_on:
      - postgres
      - redis
    networks:
      - backend

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    environment:
      - 'REDIS_HOST=redis'
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: