version: '3'
services:
  clients_postgres:
    image: 'postgres:latest'
    container_name: 'clients_postgres'
    environment:
      - 'POSTGRES_DB=clients'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5432"

    networks:
      - backend

  app:
    build: /.
    container_name: 'clients-java-app'
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/clients'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=0000'
    depends_on:
      - clients_postgres
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: